---
- hosts: elasticsearch_nomad_clients
  tasks:
  - name: Check that the java driver is healthy
    shell: nomad node status -verbose -self -json | jq '.Drivers.java.Healthy'
    register: java_driver_healthy
    failed_when: java_driver_healthy.stdout != "true"
  - name: Health of java driver
    debug: 
      var: java_driver_healthy.stdout

