---
# from https://gist.github.com/rbq/886587980894e98b23d0eee2a1d84933
# which follows https://docs.docker.com/install/linux/docker-ce/ubuntu/
- hosts: nomad_clients
  become: true
  tasks:
  - name: Copy hcl files over
    copy:
      src: hcl_files/
      dest: /home/ubuntu
      owner: ubuntu
      group: ubuntu
  - name: hcl templates with IPs
    template:
      src: hcl_files/{{ item }}.j2
      dest: /home/ubuntu/{{ item }}
      owner: ubuntu
      group: ubuntu
    loop: 
      - elasticsearch_docker.hcl
      - kibana.hcl
  - name: Create pipeline config dir for logstash
    file: 
      path: /home/ubuntu/pipeline
      state: directory
  - name: Logstash pipeline config
    template:
      src: config_files/pipeline/logstash.conf.j2
      dest: /home/ubuntu/pipeline/logstash.conf
      owner: ubuntu
      group: ubuntu
