--- 
- hosts: elasticsearch_nomad_clients
  become: true
  tasks:
  - name: set nomad node_class to elasticsearch
    lineinfile:
      path: /opt/nomad/config/default.hcl
      insertafter: '^  enabled = true$'
      line: '  node_class="elasticsearch"'
    register: node_class_set
    notify: Restart nomad
  - debug:
      msg: Loooookyhere " {{ groups['elasticsearch_nomad_clients'][0] }} " 
  - name: Increase max file descriptors 
    pam_limits:
      domain: "*"
      limit_type: '-'
      limit_item: nofile
      value: 65535
      comment: elasticsearch prod mode
  - name: Install Elasticsearch, but don't start it
    import_role:
      name: elastic.elasticsearch
    vars:
      es_data_dirs:
        - "/opt/elasticsearch/data"
      es_log_dir: "/var/log"
      es_config:
        discovery.seed_providers: file
        node.name: "{{ ansible_nodename }}"
        cluster.name: "searchmeetup-munich"
        network.host: "{{ ansible_default_ipv4.address }}"
      es_heap_size: 1g
      es_start_service: false
  - name: Create discovery seed file
    copy:
      content: " {% for host in groups['elasticsearch_nomad_clients'] %} {{ hostvars[host]['ansible_facts'].default_ipv4.address | regex_replace('([0-9.].*)','\\1\n') }} {% endfor %}  "
      dest: /etc/elasticsearch/unicast_hosts.txt
      owner: elasticsearch
    register: ip_addresses_present
  - name: Remove leading blanks in seed file
    replace:
      path: /etc/elasticsearch/unicast_hosts.txt
      regexp: '^  (.[0-9.])'
      replace: '\1'

  - name: create data dir
    file:
      path: /opt/elasticsearch/data
      state: directory
      mode: '0755'
      owner: elasticsearch
  - name: Use java that was bundled with elasticsearch
    alternatives:
      name: java
      link: /usr/bin/java
      path: /usr/share/elasticsearch/jdk/bin/java
  handlers:
    - name: Restart nomad
      supervisorctl:
        name: nomad
        state: restarted
